### ISSUE TITLE
Unable to find property selected in class PaperTabs

### ISSUE THREAD

**Issue by CRTX** [dart-lang/custom-element-apigen#50]
I ran `pub run custom_element_apigen:update polymer_elements_config.yaml` using `polymer_elements_config.yaml` from https://github.com/dart-lang/polymer_elements/blob/master/polymer_elements_config.yaml

I however got the following error:

```
198 of 204: lib/src/paper-tabs/paper-tabs.htmlUnhandled exception:                 
unable to find property selected in class PaperTabs
#0      _applyTypeOverrides.<anonymous closure>.<anonymous closure> (package:custom_element_apigen/generate_dart_api.dart:193)
#1      YamlNode&MapMixin.forEach (dart:collection/maps.dart:53)
#2      _applyTypeOverrides.<anonymous closure> (package:custom_element_apigen/generate_dart_api.dart:190)
#3      YamlNode&MapMixin.forEach (dart:collection/maps.dart:53)
#4      _applyTypeOverrides (package:custom_element_apigen/generate_dart_api.dart:178)
#5      _parseFile.<_parseFile_async_body> (package:custom_element_apigen/generate_dart_api.dart:164)
#6      _RootZone.runUnary (dart:async/zone.dart:1204)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#10     _Future._completeWithValue (dart:async/future_impl.dart:477)
#11     Future.wait.<anonymous closure> (dart:async/future.dart:299)
#12     _RootZone.runUnary (dart:async/zone.dart:1204)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#16     _Future._completeWithValue (dart:async/future_impl.dart:477)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Is there a way I can fix this?

**Comment by jakemac53** [comment]
It sounds like maybe the `selected` property no longer exists on paper-tabs, or maybe it got renamed. You should just be able to edit the polymer_elements_config.yaml accordingly.
