### ISSUE TITLE
pub run custom_element_apigen:update configfile.yaml fails

### ISSUE THREAD

**Issue by terrasea** [dart-lang/custom-element-apigen#54]
Currently 

```pub run custom_element_apigen:update configfile.yaml```

fails completely with the following output

```
1 of 2: lib/src/login-flip/src/login-flip.htmlUnhandled exception:
ProcessException: No such file or directory
  Command: packages/custom_element_apigen/src/js/process_elements.sh lib/src/login-flip/src/login-flip.html
#0      _parseFile.<_parseFile_async_body> (package:custom_element_apigen/generate_dart_api.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1410)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Dart:  Dart VM version: 1.22.0-dev.2.0 (Fri Dec 16 01:52:16 2016) on "linux_x64"
OS: Gentoo Linux

**Comment by andrey-zakharov** [comment]
Confirmed.
Looks like project is abandoned.

**Comment by terrasea** [comment]
I've not looked at this for a while, but I understood they were going to be opening  Polymer Dart to the community, with the idea of turning it into a community driven project. I hope they do, as I prefer Polymer to Angular for creating elements.

There is a pull request that will solve this issue, but no one in authority seems to be willing and/or able to merge the pull request. Let alone make a new version and publish it to pub
